version: "3.8"

services:
  search:
    build:
      target: search-image
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "127.0.0.1:5064:5064"
    environment:
      - HOST=0.0.0.0
      - PORT=5064
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    ports:
      - "127.0.0.1:9201:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data:
